// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbrngqmfaubqdsajvmer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicm5ncW1mYXVicWRzYWp2bWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTIwOTksImV4cCI6MjA1ODkyODA5OX0.0yVQmWtPmnRRHqyxlKVOqP74RDHefTbynSBI60o-k5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);